# =============================================================================
# WireGuard VPN client — the gateway dials the platform's Talos control-plane
# WireGuard server so home/LAN traffic can reach the cluster's internal networks
# (the WG subnet, the Hetzner nodes, and the pod network) over an encrypted
# tunnel, instead of exposing those services publicly.
#
# STATUS: prepared, NOT yet applicable. Two gates remain before this is merged
# and applied:
#   1. Provider — needs a `filipowm/unifi` release that includes the
#      `purpose = "vpn-client"` / `vpn_type = "wireguard-client"` /
#      `wireguard_client_*` schema (filipowm/terraform-provider-unifi#147).
#      When released, bump the pin in versions.tf + .terraform.lock.hcl.
#   2. Server — needs the platform's Talos control-plane WireGuard server to
#      exist, for the real peer public key + endpoint. Fill the locals below;
#      both are non-secret (a public key and a public IP).
#
# The gateway's own private key is generated by the provider (the controller
# does not generate one) and kept in state; its public key is exposed as an
# output to add as a peer on the WG server.
# =============================================================================

locals {
  # TODO(platform WG server): replace these placeholders with the real values
  # once the Talos control-plane WireGuard server exists. Both are non-secret.
  cluster_wg_peer_public_key = "REPLACE_WITH_TALOS_WG_SERVER_PUBLIC_KEY"
  cluster_wg_peer_endpoint   = "REPLACE_WITH_CONTROL_PLANE_PUBLIC_IP"
  cluster_wg_peer_port       = 51820

  # The gateway's own address on the tunnel. WG subnet is 10.200.0.0/24; the
  # server is .1, this client is .2.
  cluster_wg_tunnel_address = "10.200.0.2/32"

  # Only these destinations go over the tunnel (vpn_client_default_route stays
  # false — this is not a full-tunnel internet VPN).
  cluster_wg_routes = [
    "10.200.0.0/24", # WireGuard subnet
    "10.0.0.0/16",   # Hetzner private network (nodes)
    "10.244.0.0/16", # pod network
  ]
}

# import-first:new Brand-new WireGuard VPN client; the network has no VPN client yet, so it is created (not imported).
resource "unifi_network" "cluster_wireguard" {
  name     = "cluster-wireguard"
  purpose  = "vpn-client"
  vpn_type = "wireguard-client"

  # Required for a wireguard-client: the gateway's own tunnel interface address.
  subnet = local.cluster_wg_tunnel_address

  wireguard_interface   = "wan"
  wireguard_client_mode = "manual"

  # The remote WireGuard server (the Talos control plane) this gateway dials.
  wireguard_client_peer_ip         = local.cluster_wg_peer_endpoint
  wireguard_client_peer_port       = local.cluster_wg_peer_port
  wireguard_client_peer_public_key = local.cluster_wg_peer_public_key

  # Required for a wireguard-client: interface DNS. A public resolver is fine
  # here; internal name resolution is handled by UniFi local DNS records.
  dhcp_dns = ["1.1.1.1"]

  vpn_client_default_route = false
  uid_vpn_custom_routing   = local.cluster_wg_routes

  # x_wireguard_private_key is intentionally omitted: the provider generates the
  # gateway's key pair (the controller does not) and keeps it in state.
}

# Add this public key as a peer on the Talos control-plane WireGuard server.
output "cluster_wireguard_gateway_public_key" {
  description = "The gateway's WireGuard public key; add it as a peer on the Talos WG server."
  value       = unifi_network.cluster_wireguard.wireguard_public_key
}
