# WireGuard VPN client: the UniFi gateway dials a remote WireGuard server so
# home/LAN traffic reaches the cluster's internal networks over an encrypted
# tunnel instead of exposing them publicly.
#
# The gateway's own private key is generated by the provider (the controller
# does not generate one); its public key is exposed as an output to add as a
# peer on the remote server.
#
# import-first:new Brand-new VPN client; the network has no WireGuard VPN client yet.
resource "unifi_network" "this" {
  name     = var.name
  purpose  = "vpn-client"
  vpn_type = "wireguard-client"

  # The gateway's own tunnel interface address (required for a wireguard-client).
  subnet = var.tunnel_address

  wireguard_interface   = var.egress_interface
  wireguard_client_mode = "manual"

  wireguard_client_peer_ip         = var.peer_endpoint
  wireguard_client_peer_port       = var.peer_port
  wireguard_client_peer_public_key = var.peer_public_key

  # Interface DNS is required by the controller for a wireguard-client.
  dhcp_dns = var.interface_dns

  vpn_client_default_route = false
  uid_vpn_custom_routing   = var.routes
}
